### ISSUE TITLE
can not build image locally

### ISSUE THREAD

**Issue by lyskov** [coursera/coursera-labs#21]
I am trying to build example images locally following readme and getting the following error. Thanks,
```% ./run-lab/run.sh build jupyter/scipy-notebook/v2 --add-submit-button
******************************
*
*    Building base/scipy-notebook-v2.0 (with submit button: True)...
*
******************************

docker build \
    -t base/scipy-notebook-v2.0 \
    /Users/abc/coursera-labs/jupyter/scipy-notebook/v2/share

Traceback (most recent call last):
  File "coursera-lab.py", line 275, in <module>
    main()
  File "coursera-lab.py", line 270, in main
    execute_build(build_dir, manifest, args.add_submit_button)
  File "coursera-lab.py", line 140, in execute_build
    build_image(share_build_dir, image_tag)
  File "coursera-lab.py", line 94, in build_image
    subprocess.call(command)
  File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```

**Comment by lyskov** [comment]
ok, i have found the issue: apparently this line https://github.com/coursera/coursera-labs/blob/master/run-lab/Dockerfile#L5 occasionally terminate with zero exit-code while script actually failed (ie timeouted). It might worth to replace it with something like `RUN curl -sSL https://get.docker.com/ | sh && which docker`. Thanks,
